### ISSUE TITLE
Add default CustomTooltip

### ISSUE THREAD

**Issue by rafaellehmkuhl** [mewtlu/vue-tooltip-directive#1]
First of all, awesome lib! Exactly what I was looking for!

An idea: could we have a CustomTooltip component, like the one you suggest in the examples, as the default custom tooltip component? This way it would be a matter of adding the lib, and if one needs to customize the component, it creates it's own.

**Comment by mewtlu** [comment]
Great idea! I'll add that in when I get a chance, or feel free to PR it yourself if you'd like.

**Comment by rafaellehmkuhl** [comment]
> Great idea! I'll add that in when I get a chance, or feel free to PR it yourself if you'd like.

Will do!
